# <center>NumPy</center>

*Numerical Python*

![Imgur](https://i.imgur.com/BnS2grq.jpg)

In [2]:
import numpy as np

In [3]:
data = np.random.randn(2, 3)
data

array([[-1.35741207,  0.7268042 ,  0.24690437],
       [ 0.89319408, -1.64917517, -0.28688761]])

In [4]:
data +data +10000

array([[ 9997.28517586, 10001.45360841, 10000.49380873],
       [10001.78638817,  9996.70164966,  9999.42622478]])

In [5]:
data.shape

(2, 3)

In [6]:
data.dtype

dtype('float64')

In [7]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [8]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr2.ndim

2

In [10]:
arr2.shape

(2, 4)

In [11]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.empty((2,3,4))

array([[[6.23042070e-307, 1.89146896e-307, 1.37961302e-306,
         1.05699242e-307],
        [8.01097889e-307, 1.78020169e-306, 7.56601165e-307,
         1.02359984e-306],
        [1.11259940e-306, 1.11261774e-306, 1.78019625e-306,
         1.11261774e-306]],

       [[1.78019625e-306, 6.89805151e-307, 7.56592338e-307,
         6.89807188e-307],
        [1.11261774e-306, 1.78019625e-306, 1.78021798e-306,
         8.34449382e-308],
        [1.78022342e-306, 8.06635958e-308, 1.42410974e-306,
         3.20558931e-317]]])

In [14]:
#like bulit-in range()
np.arange(17)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [15]:
np.ones_like(np.random.randn(3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.zeros_like(arr2)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [17]:
#empty_like

In [18]:
np.eye(4,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

In [19]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [20]:
arr1 = np.array([1,2,3],dtype=np.float64)
arr1.dtype

dtype('float64')

![dtype1](img/dtype1.png)

![dtype2](img/dtype2.png)

In [21]:
arr1.dtype

dtype('float64')

In [22]:
int_arr1 = arr1.astype(np.int64)
int_arr1.dtype

dtype('int64')

In [23]:
numeric_strings = np.array(['1.25','-9.6','43'], dtype = np.string_)
numeric_strings.astype(np.float64)

array([ 1.25, -9.6 , 43.  ])

In [24]:
int_array = np.arange(10)

In [25]:
calibers = np.array([.22, .270, .357, .444, .33, .50], dtype=np.float64)

In [26]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

**调用astype一定会创建一个新数组（原数据的拷贝）**

矢量化 vectorization

In [27]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])

In [28]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [29]:
arr* arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [30]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [32]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

不同大小数组进行运算 广播（broadcasting）

In [33]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr[5:8]

array([5, 6, 7])

In [35]:
arr[5:8] = 12 #broadcasting
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [36]:
arr_slice = arr[5:8] #change arr while change arr_slice
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [37]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [38]:
arr_slice2 = arr[5:8].copy()
arr_slice2[:] = 100
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [39]:
arr2d = np.arange(1,16).reshape((3, 5))

In [40]:
arr2d[0][2]

3

In [41]:
arr2d[0,2]

3

In [42]:
arr3d = np.arange(1,13).reshape((2,2,3))
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [43]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [45]:
arr3d[0] = old_values
arr3d
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [47]:
arr2d
arr2d[:2, 1:]

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10]])

In [48]:
arr2d[2,1:]

array([12, 13, 14, 15])

In [49]:
arr2d[:,1:3]

array([[ 2,  3],
       [ 7,  8],
       [12, 13]])

In [50]:
arr2d[:,1:3] = 0

In [51]:
arr2d

array([[ 1,  0,  0,  4,  5],
       [ 6,  0,  0,  9, 10],
       [11,  0,  0, 14, 15]])

In [52]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
data

array([[ 0.45214097, -0.85285898,  1.79560669,  0.61857346],
       [-0.42600404, -2.8903025 , -0.75339746,  0.55595698],
       [-0.27406869,  0.74846379,  0.3154172 ,  0.91049974],
       [ 0.37317268, -0.7288558 ,  1.50266878,  0.21878468],
       [ 0.99905561,  1.64588916, -0.80458671,  1.35806652],
       [-0.20675731,  0.25504842, -1.58578134, -0.68644463],
       [ 1.53435615, -0.7132394 , -0.46576097, -1.3882666 ]])

In [53]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [54]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [55]:
data[names == 'Bob']

array([[ 0.45214097, -0.85285898,  1.79560669,  0.61857346],
       [ 0.37317268, -0.7288558 ,  1.50266878,  0.21878468]])

In [56]:
data[names == 'Bob', 2:]

array([[1.79560669, 0.61857346],
       [1.50266878, 0.21878468]])

In [57]:
data[names != 'Bob']

array([[-0.42600404, -2.8903025 , -0.75339746,  0.55595698],
       [-0.27406869,  0.74846379,  0.3154172 ,  0.91049974],
       [ 0.99905561,  1.64588916, -0.80458671,  1.35806652],
       [-0.20675731,  0.25504842, -1.58578134, -0.68644463],
       [ 1.53435615, -0.7132394 , -0.46576097, -1.3882666 ]])

In [58]:
data[~(names == 'Bob')]

array([[-0.42600404, -2.8903025 , -0.75339746,  0.55595698],
       [-0.27406869,  0.74846379,  0.3154172 ,  0.91049974],
       [ 0.99905561,  1.64588916, -0.80458671,  1.35806652],
       [-0.20675731,  0.25504842, -1.58578134, -0.68644463],
       [ 1.53435615, -0.7132394 , -0.46576097, -1.3882666 ]])

In [59]:
data[(names == 'Bob') | (names == 'Will')]

array([[ 0.45214097, -0.85285898,  1.79560669,  0.61857346],
       [-0.27406869,  0.74846379,  0.3154172 ,  0.91049974],
       [ 0.37317268, -0.7288558 ,  1.50266878,  0.21878468],
       [ 0.99905561,  1.64588916, -0.80458671,  1.35806652]])

and, or 在布尔型数组中无效

In [60]:
data[data < 0 ] = 0
data

array([[0.45214097, 0.        , 1.79560669, 0.61857346],
       [0.        , 0.        , 0.        , 0.55595698],
       [0.        , 0.74846379, 0.3154172 , 0.91049974],
       [0.37317268, 0.        , 1.50266878, 0.21878468],
       [0.99905561, 1.64588916, 0.        , 1.35806652],
       [0.        , 0.25504842, 0.        , 0.        ],
       [1.53435615, 0.        , 0.        , 0.        ]])

In [61]:
data[names != 'Joe'] = 8
data

array([[8.        , 8.        , 8.        , 8.        ],
       [0.        , 0.        , 0.        , 0.55595698],
       [8.        , 8.        , 8.        , 8.        ],
       [8.        , 8.        , 8.        , 8.        ],
       [8.        , 8.        , 8.        , 8.        ],
       [0.        , 0.25504842, 0.        , 0.        ],
       [1.53435615, 0.        , 0.        , 0.        ]])

## 花式索引 Fancy indexing

In [62]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [63]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [64]:
arr[[-3,-5,-5]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [65]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [66]:
arr[[1,5,7,2],[0,3,2,1]]

array([ 4, 23, 30,  9])

In [67]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [68]:
arr[np.ix_([1,5,7,2],[0,3,1,2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [69]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [70]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [71]:
arr = np.random.randn(6,3)
np.dot(arr.T, arr) # 3,6 6,3

array([[10.93480028,  0.97342949, -6.65845717],
       [ 0.97342949,  3.80790203,  1.08365376],
       [-6.65845717,  1.08365376, 15.74973184]])

In [72]:
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [73]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [74]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

## swapaxes也是返回原数据的视图

In [75]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [85]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [88]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [107]:
x = np.random.randn(8)
y = np.random.randn(8)
x

array([-0.28311775,  1.77847347, -0.41718903, -0.64849459,  0.01764698,
        0.19442194,  0.07787518, -0.42071897])

In [108]:
np.maximum(x,y)

array([-0.28311775,  1.77847347, -0.12933347, -0.64849459,  1.6368845 ,
        1.92774335,  2.01239229,  0.11479163])

In [116]:
divmod(11,3)

(3, 2)

In [114]:
arr = np.random.randn(7) * 5
arr

array([ 5.62611936, -4.03706109, -2.64939857,  2.48313819,  2.23486188,
        7.45553274,  0.79800588])

In [115]:
np.modf(arr)

(array([ 0.62611936, -0.03706109, -0.64939857,  0.48313819,  0.23486188,
         0.45553274,  0.79800588]), array([ 5., -4., -2.,  2.,  2.,  7.,  0.]))

In [117]:
arr

array([ 5.62611936, -4.03706109, -2.64939857,  2.48313819,  2.23486188,
        7.45553274,  0.79800588])